// ZsLinkXmlGenerator.cs — AOT / IL2CPP link.xml generator.
//
// Run via: Tools > ZScript > Generate IL2CPP link.xml
//
// IL2CPP's code stripper removes types and members that appear unreachable at
// build time.  ZScript accesses C# types via reflection (through ZsObjectPool and
// the IZScriptExport discovery mechanism), so those types must be preserved
// explicitly in a link.xml file.
//
// The generated file covers:
//   1. Every type marked [ZScriptExport] — full preservation ("preserve all").
//   2. Every IZScriptExport implementation (generated or hand-written) — full preserve.
//   3. The entire ZScript.Runtime assembly (ZsNative, ZsObjectPool, etc.) — full preserve.
//   4. The ZScriptGenerated namespace (if it exists) — full preserve.
//
// The file is written to Assets/link.xml, which Unity reads automatically.
// Re-run this tool after adding or removing [ZScriptExport] types or IZScriptExport
// implementations, and before making an IL2CPP build.
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace ZScript.Editor
{
    public static class ZsLinkXmlGenerator
    {
        private const string OutputPath = "Assets/link.xml";

        [MenuItem("Tools/ZScript/Generate IL2CPP link.xml")]
        public static void Generate()
        {
            // Collect types to preserve.
            var byAssembly = new Dictionary<string, List<string>>(StringComparer.Ordinal);

            void AddType(Type t)
            {
                string asmName = t.Assembly.GetName().Name;
                if (!byAssembly.TryGetValue(asmName, out var list))
                    byAssembly[asmName] = list = new List<string>();
                list.Add(t.FullName);
            }

            // 1. [ZScriptExport] types
            foreach (var t in FindTaggedTypes<ZScriptExportAttribute>())
                AddType(t);

            // 2. IZScriptExport implementations
            foreach (var t in FindImplementors(typeof(IZScriptExport)))
                AddType(t);

            // Build XML
            var sb = new StringBuilder();
            sb.AppendLine("<!--");
            sb.AppendLine("  Auto-generated by ZScript IL2CPP link.xml Generator.");
            sb.AppendLine("  Re-run Tools > ZScript > Generate IL2CPP link.xml after changing");
            sb.AppendLine("  [ZScriptExport] types or IZScriptExport implementations.");
            sb.AppendLine("-->");
            sb.AppendLine("<linker>");

            // 3. Always preserve the entire ZScript.Runtime assembly.
            sb.AppendLine("  <!-- ZScript runtime — must never be stripped. -->");
            sb.AppendLine("  <assembly fullname=\"ZScript.Runtime\" preserve=\"all\"/>");
            sb.AppendLine();

            // 4. ZScriptGenerated (generated bindings)
            sb.AppendLine("  <!-- Generated export bindings. -->");
            sb.AppendLine("  <assembly fullname=\"Assembly-CSharp\" preserve=\"nothing\">");
            sb.AppendLine("    <namespace fullname=\"ZScriptGenerated\" preserve=\"all\"/>");
            sb.AppendLine("  </assembly>");
            sb.AppendLine();

            // 5. User-specific types grouped by assembly
            if (byAssembly.Count > 0)
            {
                sb.AppendLine("  <!-- User types accessed by ZScript via [ZScriptExport] or IZScriptExport. -->");
                foreach (var kv in byAssembly.OrderBy(kv => kv.Key))
                {
                    sb.AppendLine($"  <assembly fullname=\"{kv.Key}\">");
                    foreach (string typeName in kv.Value.Distinct().OrderBy(t => t))
                        sb.AppendLine($"    <type fullname=\"{typeName}\" preserve=\"all\"/>");
                    sb.AppendLine($"  </assembly>");
                }
            }

            sb.AppendLine("</linker>");

            File.WriteAllText(OutputPath, sb.ToString(), Encoding.UTF8);
            AssetDatabase.Refresh();

            int typeCount = byAssembly.Values.Sum(l => l.Count);
            Debug.Log($"[ZScript] Generated {OutputPath} — {typeCount} user type(s) preserved.");
            if (!Application.isBatchMode)
            {
                EditorUtility.DisplayDialog(
                    "ZScript link.xml Generator",
                    $"link.xml written to {OutputPath}\n\n" +
                    $"Preserved:\n" +
                    $"  • ZScript.Runtime assembly (all types)\n" +
                    $"  • ZScriptGenerated namespace\n" +
                    $"  • {typeCount} user type(s) with [ZScriptExport] or IZScriptExport",
                    "OK");
            }
        }

        // ----------------------------------------------------------------
        // Discovery helpers
        // ----------------------------------------------------------------

        private static IEnumerable<Type> FindTaggedTypes<TAttr>() where TAttr : Attribute
        {
            foreach (var asm in UserAssemblies())
            {
                foreach (var t in SafeGetTypes(asm))
                {
                    if (t.GetCustomAttribute<TAttr>() != null)
                        yield return t;
                }
            }
        }

        private static IEnumerable<Type> FindImplementors(Type iface)
        {
            foreach (var asm in UserAssemblies())
            {
                foreach (var t in SafeGetTypes(asm))
                {
                    if (t.IsAbstract || t.IsInterface) continue;
                    if (iface.IsAssignableFrom(t))
                        yield return t;
                }
            }
        }

        private static IEnumerable<Assembly> UserAssemblies()
        {
            foreach (var asm in AppDomain.CurrentDomain.GetAssemblies())
            {
                string name = asm.GetName().Name;
                if (name.StartsWith("UnityEngine",  StringComparison.Ordinal) ||
                    name.StartsWith("UnityEditor",  StringComparison.Ordinal) ||
                    name.StartsWith("Unity.",       StringComparison.Ordinal) ||
                    name.StartsWith("System",       StringComparison.Ordinal) ||
                    name.StartsWith("mscorlib",     StringComparison.Ordinal) ||
                    name.StartsWith("Mono.",        StringComparison.Ordinal) ||
                    name.StartsWith("nunit",        StringComparison.Ordinal))
                    continue;
                yield return asm;
            }
        }

        private static IEnumerable<Type> SafeGetTypes(Assembly asm)
        {
            try   { return asm.GetTypes(); }
            catch { return Array.Empty<Type>(); }
        }
    }
}
