// ExportCodeWriter.cs — Generates C++ binding snippet + C# dispatch stub
// for each [ZScriptExport] type.
using System.Text;

namespace ZScriptExportGen;

public static class ExportCodeWriter
{
    public static void WriteAll(IReadOnlyList<ExportedTypeInfo> types,
                                string cppOutputDir,
                                string csOutputPath)
    {
        Directory.CreateDirectory(cppOutputDir);

        foreach (var t in types)
            WriteCppSnippet(t, cppOutputDir);

        WriteCSharpStubs(types, csOutputPath);
        WriteCppBulkEntryPoint(types, cppOutputDir);
    }

    // -----------------------------------------------------------------------
    // C++ snippet — one file per exported type
    // -----------------------------------------------------------------------
    private static void WriteCppSnippet(ExportedTypeInfo t, string outputDir)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// AUTO-GENERATED by ZScriptExportGen — do not edit manually.");
        sb.AppendLine($"// [ZScriptExport] type: {t.CsName} → ZScript name: \"{t.ZsName}\"");
        sb.AppendLine("#include \"vm.h\"");
        sb.AppendLine();
        sb.AppendLine("namespace zscript_export {");
        sb.AppendLine();
        sb.AppendLine($"void register_{t.SafeName}(zscript::VM& vm) {{");
        sb.AppendLine($"    zscript::Value cls = zscript::Value::from_table();");
        sb.AppendLine($"    auto* tbl = cls.as_table();");
        sb.AppendLine($"    tbl->set(\"__name\", zscript::Value::from_string(\"{t.ZsName}\"));");
        sb.AppendLine();

        bool hasInstanceMethods = t.Members.Any(m =>
            m.Kind is ExportedMemberKind.Method or ExportedMemberKind.GenericMethod);

        if (t.Kind != ExportedTypeKind.Static)
        {
            // __index
            sb.AppendLine("    tbl->set(\"__index\", zscript::Value::from_native(\"__index\",");
            sb.AppendLine("        [](std::vector<zscript::Value> args) -> std::vector<zscript::Value> {");
            sb.AppendLine("        if (args.size() < 2 || !args[0].is_table() || !args[1].is_string())");
            sb.AppendLine("            return {zscript::Value::nil()};");
            sb.AppendLine("        int64_t handle = args[0].as_table()->get(\"__handle\").as_int();");
            sb.AppendLine("        const std::string& key = args[1].as_string();");
            sb.AppendLine("        (void)handle;");

            foreach (var m in t.Members.Where(m =>
                m.Kind is ExportedMemberKind.Property or ExportedMemberKind.Field))
            {
                string esc = m.ZsName.Replace("\"", "\\\"");
                sb.AppendLine($"        if (key == \"{esc}\") {{");
                sb.AppendLine($"            // TODO: route to C# zs_export_get_{t.SafeName}_{m.CsName}");
                sb.AppendLine($"            return {{zscript::Value::nil()}};");
                sb.AppendLine($"        }}");
            }

            foreach (var m in t.Members.Where(m =>
                m.Kind is ExportedMemberKind.Method or ExportedMemberKind.GenericMethod))
            {
                string esc = m.ZsName.Replace("\"", "\\\"");
                sb.AppendLine($"        if (key == \"{esc}\") {{");
                sb.AppendLine($"            return {{zscript::Value::from_native(\"{esc}\",");
                sb.AppendLine($"                [handle](std::vector<zscript::Value> margs) -> std::vector<zscript::Value> {{");
                sb.AppendLine($"                    // TODO: route to C# zs_export_call_{t.SafeName}_{m.CsName}");
                sb.AppendLine($"                    return {{zscript::Value::nil()}};");
                sb.AppendLine($"                }})");
                sb.AppendLine($"            }};");
                sb.AppendLine($"        }}");
            }

            sb.AppendLine("        return {zscript::Value::nil()};");
            sb.AppendLine("    }));");
            sb.AppendLine();

            // __newindex (writable properties / fields)
            var writable = t.Members
                .Where(m => m.Kind is ExportedMemberKind.Property or ExportedMemberKind.Field)
                .ToArray();
            if (writable.Length > 0)
            {
                sb.AppendLine("    tbl->set(\"__newindex\", zscript::Value::from_native(\"__newindex\",");
                sb.AppendLine("        [](std::vector<zscript::Value> args) -> std::vector<zscript::Value> {");
                sb.AppendLine("        if (args.size() < 3) return {};");
                sb.AppendLine("        int64_t handle = args[0].as_table()->get(\"__handle\").as_int();");
                sb.AppendLine("        const std::string& key = args[1].as_string();");
                sb.AppendLine("        (void)handle;");
                foreach (var m in writable)
                {
                    string esc = m.ZsName.Replace("\"", "\\\"");
                    sb.AppendLine($"        if (key == \"{esc}\") {{");
                    sb.AppendLine($"            // TODO: route to C# zs_export_set_{t.SafeName}_{m.CsName}");
                    sb.AppendLine($"            return {{}};");
                    sb.AppendLine($"        }}");
                }
                sb.AppendLine("        return {};");
                sb.AppendLine("    }));");
                sb.AppendLine();
            }

            // __call for constructable types
            if (t.Kind is ExportedTypeKind.PureCSharp or ExportedTypeKind.Struct)
            {
                sb.AppendLine("    tbl->set(\"__call\", zscript::Value::from_native(\"__call\",");
                sb.AppendLine("        [](std::vector<zscript::Value> args) -> std::vector<zscript::Value> {");
                sb.AppendLine($"        // TODO: route to C# zs_export_new_{t.SafeName}");
                sb.AppendLine("        return {zscript::Value::nil()};");
                sb.AppendLine("    }));");
                sb.AppendLine();
            }
        }
        else
        {
            // Static class: expose each member directly on the table.
            foreach (var m in t.Members)
            {
                string esc = m.ZsName.Replace("\"", "\\\"");
                sb.AppendLine($"    tbl->set(\"{esc}\", zscript::Value::from_native(\"{esc}\",");
                sb.AppendLine($"        [](std::vector<zscript::Value> args) -> std::vector<zscript::Value> {{");
                sb.AppendLine($"        // TODO: route to C# zs_export_static_{t.SafeName}_{m.CsName}");
                sb.AppendLine($"        return {{zscript::Value::nil()}};");
                sb.AppendLine("    }));");
            }
            sb.AppendLine();
        }

        sb.AppendLine($"    vm.set_global(\"{t.ZsName}\", cls);");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("} // namespace zscript_export");

        File.WriteAllText(
            Path.Combine(outputDir, $"{t.SafeName}_export.cpp"),
            sb.ToString(), Encoding.UTF8);
    }

    // -----------------------------------------------------------------------
    // C# dispatch stubs — one partial class with a static delegate per member
    // -----------------------------------------------------------------------
    private static void WriteCSharpStubs(IReadOnlyList<ExportedTypeInfo> types, string outputPath)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// AUTO-GENERATED by ZScriptExportGen — do not edit manually.");
        sb.AppendLine("using System;");
        sb.AppendLine("using UnityEngine;");
        sb.AppendLine();
        sb.AppendLine("namespace ZScript");
        sb.AppendLine("{");
        sb.AppendLine("    public static partial class ZsExportDispatch");
        sb.AppendLine("    {");

        foreach (var t in types)
        {
            sb.AppendLine($"        // ── [{t.CsName}] ZScript name: \"{t.ZsName}\" ──");
            sb.AppendLine($"        #region {t.ZsName}");

            foreach (var m in t.Members)
            {
                string fnName = m.Kind switch
                {
                    ExportedMemberKind.Property or ExportedMemberKind.Field
                        => $"zs_export_get_{t.SafeName}_{m.CsName}",
                    _ => $"zs_export_call_{t.SafeName}_{m.CsName}"
                };

                // Build param doc string for the comment.
                string paramDoc = m.ParamTypes.Length == 0
                    ? ""
                    : string.Join(", ", m.ParamTypes.Zip(m.ParamNames, (ty, name) => $"{ty} {name}"));

                sb.AppendLine($"        // {t.CsName}.{m.CsName}({paramDoc}) -> {m.ReturnType}");
                sb.AppendLine($"        public static ZsNativeFn {fnName} = (vm, argc, argv) =>");
                sb.AppendLine("        {");

                if (m.Kind is ExportedMemberKind.Property or ExportedMemberKind.Field)
                {
                    sb.AppendLine("            if (argc < 1) return ZsNative.zs_value_nil();");
                    sb.AppendLine("            long handle = ZsNative.zs_value_as_int(argv[0]);");
                    sb.AppendLine($"            var obj = ZsObjectPool.Global?.Get<{t.CsName}>(handle);");
                    sb.AppendLine($"            if (obj == null) return ZsNative.zs_value_nil();");
                    sb.AppendLine($"            // TODO: return marshal(obj.{m.CsName})");
                }
                else if (m.Kind is ExportedMemberKind.GenericMethod)
                {
                    sb.AppendLine("            if (argc < 2) return ZsNative.zs_value_nil();");
                    sb.AppendLine("            long handle = ZsNative.zs_value_as_int(argv[0]);");
                    sb.AppendLine("            // argv[1] = T class table; read __name to get type name.");
                    sb.AppendLine("            // Use pre-generated static readonly Dictionary<string, Func<...>>");
                    sb.AppendLine($"            // TODO: generic dispatch for {t.CsName}.{m.CsName}<T>");
                }
                else
                {
                    sb.AppendLine("            if (argc < 1) return ZsNative.zs_value_nil();");
                    sb.AppendLine("            long handle = ZsNative.zs_value_as_int(argv[0]);");
                    sb.AppendLine($"            var obj = ZsObjectPool.Global?.Get<{t.CsName}>(handle);");
                    sb.AppendLine($"            if (obj == null) return ZsNative.zs_value_nil();");
                    sb.AppendLine($"            // TODO: obj.{m.CsName}(...) and marshal return");
                }

                sb.AppendLine("            return ZsNative.zs_value_nil();");
                sb.AppendLine("        };");
                sb.AppendLine();

                // Setter for writable properties/fields
                if (m.Kind is ExportedMemberKind.Property or ExportedMemberKind.Field)
                {
                    string setName = $"zs_export_set_{t.SafeName}_{m.CsName}";
                    sb.AppendLine($"        public static ZsNativeFn {setName} = (vm, argc, argv) =>");
                    sb.AppendLine("        {");
                    sb.AppendLine("            if (argc < 2) return ZsNative.zs_value_nil();");
                    sb.AppendLine("            long handle = ZsNative.zs_value_as_int(argv[0]);");
                    sb.AppendLine($"            var obj = ZsObjectPool.Global?.Get<{t.CsName}>(handle);");
                    sb.AppendLine($"            if (obj == null) return ZsNative.zs_value_nil();");
                    sb.AppendLine($"            // TODO: obj.{m.CsName} = unmarshal(argv[1])");
                    sb.AppendLine("            return ZsNative.zs_value_nil();");
                    sb.AppendLine("        };");
                    sb.AppendLine();
                }
            }

            // Constructor stub for constructable types
            if (t.Kind is ExportedTypeKind.PureCSharp or ExportedTypeKind.Struct)
            {
                sb.AppendLine($"        public static ZsNativeFn zs_export_new_{t.SafeName} = (vm, argc, argv) =>");
                sb.AppendLine("        {");
                sb.AppendLine($"            // TODO: var obj = new {t.CsName}(...); pool it; return handle");
                sb.AppendLine("            return ZsNative.zs_value_nil();");
                sb.AppendLine("        };");
                sb.AppendLine();
            }

            sb.AppendLine($"        #endregion // {t.ZsName}");
            sb.AppendLine();
        }

        sb.AppendLine("    } // class ZsExportDispatch");
        sb.AppendLine("} // namespace ZScript");

        Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
        File.WriteAllText(outputPath, sb.ToString(), Encoding.UTF8);
    }

    // -----------------------------------------------------------------------
    // C++ bulk entry point
    // -----------------------------------------------------------------------
    private static void WriteCppBulkEntryPoint(IReadOnlyList<ExportedTypeInfo> types, string outputDir)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// AUTO-GENERATED by ZScriptExportGen — do not edit manually.");
        sb.AppendLine("#include \"vm.h\"");
        sb.AppendLine();
        sb.AppendLine("namespace zscript_export {");
        sb.AppendLine();
        foreach (var t in types)
            sb.AppendLine($"void register_{t.SafeName}(zscript::VM& vm);");
        sb.AppendLine();
        sb.AppendLine("void register_all_exports(zscript::VM& vm) {");
        foreach (var t in types)
            sb.AppendLine($"    register_{t.SafeName}(vm);");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("} // namespace zscript_export");

        File.WriteAllText(
            Path.Combine(outputDir, "register_all_exports.cpp"),
            sb.ToString(), Encoding.UTF8);
    }
}
